language: cpp
script: cmake
compiler: g++
dist: focal
addons:
  apt:
    update: true
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libboost-all-dev
before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  #- make test